<?xml version="1.0"?>
<!DOCTYPE STUDENTS [
<!ELEMENT STUDENTS (STUDENT*)>
<!ELEMENT STUDENT (NAME, AGE, CLASS)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT AGE (#PCDATA)>
<!ELEMENT CLASS (#PCDATA)>
]>

<STUDENTS>
	<STUDENT>
		<NAME>HillyBilly</NAME>
		<AGE>19</AGE>
		<CLASS>10</CLASS>
	</STUDENT>
	<STUDENT>
		<NAME>Captain Kirk</NAME>
		<AGE>20</AGE>
		<CLASS>10</CLASS>
	</STUDENT>
</STUDENTS>